name: .NET 8 CI/CD Pipeline to Azure App Service

on:
  push:
    branches:
      - main    # Trigger on pushing to main branch
  pull_request:
    branches:
      - main    # Trigger on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET 8 SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release

      - name: Run tests
        run: dotnet test --configuration Release

      - name: Publish application
        run: dotnet publish --configuration Release --output ./publish

      - name: Archive published files
        uses: actions/upload-artifact@v2
        with:
          name: published-files
          path: ./publish

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensures deploy runs only after the build job is successful
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download published files
        uses: actions/download-artifact@v2
        with:
          name: published-files
          path: ./publish

      - name: Set up Azure credentials
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_APP_NAME }}      # Your Azure App Service Name
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}   # If you're using a publish profile instead of credentials
          package: ./publish  # Path to the published application
